# Generated by Django 4.2.3 on 2023-07-22 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder_app', '0002_rename_experince_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('link1', models.URLField()),
                ('link2', models.URLField()),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder_app.userprofile')),
            ],
        ),
    ]
