# Generated by Django 4.2.3 on 2023-07-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_app', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='link2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
