# Generated by Django 4.2.3 on 2023-07-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_app', '0004_alter_project_link1_alter_project_link2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
