# Generated by Django 4.2.3 on 2023-07-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_app', '0005_userprofile_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
