# Generated by Django 4.2.3 on 2023-07-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_app', '0007_remove_education_end_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_date',
        ),
        migrations.AddField(
            model_name='education',
            name='end_year',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.BigIntegerField(null=True),
        ),
    ]
